### ISSUE TITLE
Motor MeasurementにてRangeError [ERR_INDEX_OUT_OF_RANGEが発生する

### ISSUE THREAD

**Issue by alphazero55** [keigan-motor/kmconnector-js#1]
nobleを用いてKeiganの「Motor Measurement」サービスをサブスクライブしているのですが長時間稼働すると以下のようなエラーが発生します
発生頻度はマチマチで、特定できないです

対処法として何かわかりましたら教えていただければ幸いです

```
buffer.js:1015
    throw new errors.RangeError('ERR_INDEX_OUT_OF_RANGE');
    ^

RangeError [ERR_INDEX_OUT_OF_RANGE]: Index out of range
    at checkOffset (buffer.js:1015:11)
    at Uint8Array.readUInt16LE (buffer.js:1063:5)
    at Hci.onSocketData (/home/linaro/work/cow_catkin_work/src/cow/node_modules/noble/lib/hci-socket/hci.js:453:18)
    at BluetoothHciSocket.emit (events.js:127:13)
```

**Comment by keigan-motor** [comment]
ご報告有り難うございます
実行環境はどのような環境でしょうか？
（OS 及び  Node.js 、noble 、 Bluetoohアダプタ構成  ）

古い情報ですが、以下に似たような事例を見つけました。
https://github.com/noble/noble/issues/241
Windows上での問題かと思いますがnode-bluetooth-hci-socket v0.3.4で対応されているようです。

おそらく、OS及びBluetoohアダプタの組み合わせにより発生する問題かと推測します。
noble及びnode-bluetooth-hci-socketを最新にアップデートされて改善しないでしょうか？

**Comment by alphazero55** [comment]
返信遅くなりました
実行環境は以下になります

上記に記載のテスコードも実行してみましたが事象出ませんでした
http://pastebin.com/3HC5pFGZ

頻度は３０分から１時間ぐらい「Motor Measurement」サービスをサブスクライブし続けると発生したりします

# 実行環境
Linux tinkerboardOne 4.4.71+ #1 SMP Wed Nov 15 14:31:48 CST 2017 armv7l GNU/Linux
Debian GNU/Linux 9 (stretch)
node.js v9.6.1
noble@1.9.0
bluetooth-hci-socket@0.5.1

**Comment by alphazero55** [comment]
この症状時に使用したBLEは以下のUSBドングルになります
http://www2.elecom.co.jp/products/LBT-UAN05C2.html
