### ISSUE TITLE
startScanToCreateInstance(time)のtime引数を指定しても大体２秒でscanStopする

### ISSUE THREAD

**Issue by alphazero55** [keigan-motor/kmconnector-js#3]
モータ２台で引数のtime=15000でも大体２秒で`stopScan`メッセージが発生する

```
scan
startScanToCreateInstance
onDiscover NewMotor:KM-1 8TMO#304
[ 'KM-1 8TMO' ]
onDiscoverMotor:KM-1 8TMO#304
onDiscover NewMotor:KM-1 AWWO#313
[ 'KM-1 8TMO', 'KM-1 AWWO' ]
onDiscoverMotor:KM-1 AWWO#313
stopScan
onScanTimeout
```

## 実行環境
Linux tinkerboardOne 4.4.71+ #1 SMP Wed Nov 15 14:31:48 CST 2017 armv7l GNU/Linux
Debian GNU/Linux 9 (stretch)
node.js v9.6.1
noble@1.9.0
bluetooth-hci-socket@0.5.1

**Comment by alphazero55** [comment]
この症状は
- USBドングル
http://www2.elecom.co.jp/products/LBT-UAN05C2.html
- TinkerBoardのオンボードBLE

に関係なく発生します

**Comment by keigan-motor** [comment]
報告有り難うございます、修正いたしました
