### ISSUE TITLE
TinkerBoardのオンボードBLEだと接続しない

### ISSUE THREAD

**Issue by alphazero55** [keigan-motor/kmconnector-js#4]
TinkerBoard
https://www.asus.com/jp/Single-Board-Computer/Tinker-Board/

のオンボードBLEでScanしてもDiscoverしないので

`Class: KMMotorOneBLE`の`startScanToCreateInstance(time)`内を以下に変更したら上手く
DiscoverからConnectできました

```
-            noble.startScanning([KMComBLE.MOTOR_BLE_SERVICE_UUID],false);
+            noble.startScanning([KMComBLE.MOTOR_BLE_SERVICE_UUID],true);
```

ここの設定はBLEによると思うのですが外部から指定できるようにして欲しいです

**Comment by keigan-motor** [comment]
報告有り難うございます、修正いたしました
