### ISSUE TITLE
kMMotorOneBLE.EVENT_TYPE.disconnect後の再Scanおよび再接続時のcmd命令が効かない

### ISSUE THREAD

**Issue by alphazero55** [keigan-motor/kmconnector-js#5]
`KMMotorOneBLE.EVENT_TYPE.disconnect`発生時に
以下様なコードを実行後に再スキャン実施

```
KMMotorOneBLE.removeAllListeners()
KMMotorOneBLE.allDisConnect()
---5秒後---
KMConnector.KMMotorOneBLE.startScanToCreateInstance(5000, true)
```

再スキャン終了後`KMMotorOneBLE.EVENT_TYPE.connect`発生後に
`kMMotorOneBLE.cmdSpeed()`や`kMMotorOneBLE.cmdRunForward()`
実施してもkeiganが動か無くなります。もちろんdisconnectイベント発生前は動いていました

また、再スキャン後に`KMMotorOneBLE.EVENT_TYPE.motorMeasurement`を再登録しますが
イベントが発生しなくなります

よろしくお願いします

# 実行環境
Linux tinkerboardOne 4.4.71+ #1 SMP Wed Nov 15 14:31:48 CST 2017 armv7l GNU/Linux
Debian GNU/Linux 9 (stretch)
node.js v9.6.1
noble@1.9.1
bluetooth-hci-socket@0.5.1
kmconnector@0.1.6
[TinkerBoard](https://www.asus.com/jp/Single-Board-Computer/Tinker-Board/)

**Comment by alphazero55** [comment]
原因究明というよりは
上記の様なdisconnectイベント発生時の再接続の
サンプルコード等があれば嬉しいです

**Comment by keigan-motor** [comment]
報告有り難うございます、修正いたしました 
https://github.com/keigan-motor/kmconnector-js/commit/6781c4617ee20b6afd562eea0ffcd2fbf0b97ac7
