### ISSUE TITLE
モータ回転情報のリセット方法

### ISSUE THREAD

**Issue by iPre-Innovate** [keigan-motor/kmconnector-js#6]
KMMotorOneBLE.EVENT_TYPE.motorMeasurementイベントで取得可能なモータ回転情報のリセット方法はありますでしょうか？

現場は電源をOFFしないとリセットされない認識です

ドキュメントにあれば指定していただくとありがたいです

# 実行環境
Linux tinkerboardOne 4.4.71+ #1 SMP Wed Nov 15 14:31:48 CST 2017 armv7l GNU/Linux
Debian GNU/Linux 9 (stretch)
node.js v9.6.1
noble@1.9.1
bluetooth-hci-socket@0.5.1
kmconnector@0.1.6
TinkerBoard

**Comment by keigan-motor** [comment]
座標のリセットは以下の2つの方法で可能です。

A) [cmdPresetPosition(position)](https://document.keigan-motor.com/apiDocument/kmconnector-js/KMMotorOneBLE.html#cmdPresetPosition__anchor) （電源OFFと同じ）
　
B) [cmdReboot() ](https://document.keigan-motor.com/apiDocument/kmconnector-js/KMMotorOneBLE.html#cmdReboot__anchor)-> 再接続 （電源OFFと同じ）
